# Generated by Django 2.1 on 2019-01-20 22:40

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.EmailField(db_index=True, max_length=255)),
                ('course_id', models.CharField(blank=True, max_length=25, null=True)),
                ('prof_last_name', models.CharField(blank=True, max_length=225, null=True)),
                ('prof_first_name', models.CharField(blank=True, max_length=225, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('year', models.IntegerField()),
                ('term', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('student_id', models.CharField(max_length=30, unique=True)),
                ('courses', models.ManyToManyField(to='api.Course')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='class_days',
            field=models.ManyToManyField(related_name='class_days', to='api.Days'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('course_id', 'year', 'term')},
        ),
    ]
